@startuml User Login

header Sample User Management Sequence Diagram
footer Page %page% of %lastpage%
title "User Login"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:users" as routerUsers
participant "<<controllers>>\n:users" as controllersUsers
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:usersDB" as UsersDatabase

client->server ++: req.post('/login')
server->routerUsers ++: app.use('/users', usersRouter)
routerUsers -> controllersUsers ++: login()

controllersUsers -> modelUser ++: findOne({email})
modelUser -> UsersDatabase ++: findUserByEmail
UsersDatabase --> modelUser --: user

controllersUsers -> modelUser ++: matchPassword(password)
modelUser --> controllersUsers --: isMatch

alt isMatch
    controllersUsers -> controllersUsers : sendTokenResponse(user, 200, res)
    controllersUsers->client --: response({success: true, token})
else not isMatch
    controllersUsers->client --: response({success: false, msg: 'Invalid credentials'})
end

@enduml
