@startuml Get All Add-On Services

header Sample Add-On Services Sequence Diagram
footer Page %page% of %lastpage%
title "Get All Add-On Services"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:addonservices" as routerAddOnServices
participant "<<middleware>>\n:Auth" as AuthMiddleware
participant "<<controllers>>\n:addonservices" as controllersAddOnServices
participant "<<model>>\n:AddOnService" as modelAddOnService
database "<<MongoDB>>\n:addonservicesDB" as AddOnServicesDatabase

client->server ++: req.get('/addonservices')
server->routerAddOnServices ++: app.use('/addonservices', addonservicesRouter)
routerAddOnServices -> AuthMiddleware ++: protect
AuthMiddleware -> controllersAddOnServices ++: getAllAddOnService()

controllersAddOnServices -> controllersAddOnServices ++: parseFilter(req.query)
controllersAddOnServices -> modelAddOnService ++: find(filteredQuery)
modelAddOnService -> AddOnServicesDatabase ++: find(filteredQuery)
alt sort and paginate
    modelAddOnService -> AddOnServicesDatabase ++: sort(), paginate()
end
AddOnServicesDatabase --> modelAddOnService --: addonservices
controllersAddOnServices -> controllersAddOnServices ++: preparePagination()
controllersAddOnServices->client --: response({ success: true, data: addonservices, pagination })

@enduml
